inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  Include:
    - Gemfile
    - Guardfile
    - Rakefile
    - bin/howzit
    - lib/**/*.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - 'bin/howzit'
    - 'lib/howzit/task.rb'  # inspect method with long format string
    - 'lib/howzit/util.rb'  # error messages with long template strings
    - 'lib/howzit/stringutils.rb'  # Color template strings
    - 'lib/howzit/buildnote.rb'  # Some long lines in complex methods

Metrics/BlockLength:
  Max: 145
  Exclude:
    - Rakefile
    - bin/howzit
    - lib/*.rb

# Metrics limits are defined in .rubocop_todo.yml with higher values for complex methods

# Style/CaseLikeIf: if-elsif with regex captures needed for Regexp.last_match
Style/CaseLikeIf:
  Exclude:
    - 'lib/howzit/condition_evaluator.rb'

Style/RegexpLiteral:
  Exclude:
    - Guardfile

# Security/YAMLLoad: YAML.load is used intentionally to support Symbol keys
Security/YAMLLoad:
  Exclude:
    - '**/*'
