#!/bin/bash
export GLI_DEBUG=true
export EDITOR="/usr/bin/vim"
export PATH=$PATH:$GEM_HOME/bin
alias b="bundle exec bin/howzit"

shopt -s nocaseglob
shopt -s histappend
shopt -s histreedit
shopt -s histverify
shopt -s cmdhist

cd /howzit
bundle install
